# Generated by Django 4.2.1 on 2023-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_area', models.IntegerField()),
                ('property_dimensions', models.CharField(max_length=50)),
                ('property_image', models.ImageField(upload_to='')),
                ('property_description', models.TextField()),
            ],
        ),
    ]
