# Generated by Django 4.2.1 on 2023-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_propertymodel_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='property_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
